/**
 * IGCSE & A-Level 学科词汇数据
 * 贴近 Cambridge / Edexcel / AQA / OCR 等考试局通用术语
 */

const VOCAB = {
  math: [
    { term: "Absolute value", meaning: "绝对值" },
    { term: "Acute angle", meaning: "锐角" },
    { term: "Algebra", meaning: "代数" },
    { term: "Algorithm", meaning: "算法" },
    { term: "Alternate angles", meaning: "内错角" },
    { term: "Altitude", meaning: "高；海拔" },
    { term: "Angle", meaning: "角" },
    { term: "Arc", meaning: "弧" },
    { term: "Area", meaning: "面积" },
    { term: "Arithmetic sequence", meaning: "等差数列" },
    { term: "Asymptote", meaning: "渐近线" },
    { term: "Average", meaning: "平均数" },
    { term: "Axis / Axes", meaning: "轴" },
    { term: "Bar chart", meaning: "条形图" },
    { term: "Base", meaning: "底；底数" },
    { term: "Bearing", meaning: "方位角" },
    { term: "Binomial", meaning: "二项式" },
    { term: "Bisector", meaning: "平分线" },
    { term: "Capacity", meaning: "容量" },
    { term: "Chord", meaning: "弦" },
    { term: "Circle", meaning: "圆" },
    { term: "Circumference", meaning: "周长" },
    { term: "Coefficient", meaning: "系数" },
    { term: "Complementary angles", meaning: "余角" },
    { term: "Compound interest", meaning: "复利" },
    { term: "Cone", meaning: "圆锥" },
    { term: "Congruent", meaning: "全等" },
    { term: "Constant", meaning: "常数" },
    { term: "Correlation", meaning: "相关" },
    { term: "Cosine (cos)", meaning: "余弦" },
    { term: "Cube", meaning: "立方；立方体" },
    { term: "Cubic", meaning: "三次的；立方的" },
    { term: "Cylinder", meaning: "圆柱" },
    { term: "Decimal", meaning: "小数" },
    { term: "Denominator", meaning: "分母" },
    { term: "Derivative", meaning: "导数" },
    { term: "Diameter", meaning: "直径" },
    { term: "Differentiation", meaning: "微分；求导" },
    { term: "Digit", meaning: "数字" },
    { term: "Direct proportion", meaning: "正比例" },
    { term: "Discrete", meaning: "离散的" },
    { term: "Distribution", meaning: "分布" },
    { term: "Dividend", meaning: "被除数" },
    { term: "Divisor", meaning: "除数" },
    { term: "Equation", meaning: "方程" },
    { term: "Equilateral", meaning: "等边的" },
    { term: "Evaluate", meaning: "求值" },
    { term: "Even number", meaning: "偶数" },
    { term: "Expand", meaning: "展开" },
    { term: "Exponent", meaning: "指数" },
    { term: "Expression", meaning: "式子；表达式" },
    { term: "Factor", meaning: "因数；因式" },
    { term: "Factorise", meaning: "因式分解" },
    { term: "Formula", meaning: "公式" },
    { term: "Fraction", meaning: "分数" },
    { term: "Frequency", meaning: "频数；频率" },
    { term: "Function", meaning: "函数" },
    { term: "Gradient", meaning: "斜率；梯度" },
    { term: "Graph", meaning: "图像；图" },
    { term: "Hexagon", meaning: "六边形" },
    { term: "Hypotenuse", meaning: "斜边" },
    { term: "Identity", meaning: "恒等式" },
    { term: "Improper fraction", meaning: "假分数" },
    { term: "Index / Indices", meaning: "指数" },
    { term: "Inequality", meaning: "不等式" },
    { term: "Integer", meaning: "整数" },
    { term: "Integration", meaning: "积分" },
    { term: "Intercept", meaning: "截距" },
    { term: "Interest", meaning: "利息" },
    { term: "Intersection", meaning: "交集；交点" },
    { term: "Inverse", meaning: "逆；反函数" },
    { term: "Irrational number", meaning: "无理数" },
    { term: "Isosceles", meaning: "等腰的" },
    { term: "Limit", meaning: "极限" },
    { term: "Linear", meaning: "线性的" },
    { term: "Locus", meaning: "轨迹" },
    { term: "Logarithm", meaning: "对数" },
    { term: "Mean", meaning: "平均数" },
    { term: "Median", meaning: "中位数" },
    { term: "Mode", meaning: "众数" },
    { term: "Multiple", meaning: "倍数" },
    { term: "Negative number", meaning: "负数" },
    { term: "Numerator", meaning: "分子" },
    { term: "Obtuse angle", meaning: "钝角" },
    { term: "Odd number", meaning: "奇数" },
    { term: "Origin", meaning: "原点" },
    { term: "Parallelogram", meaning: "平行四边形" },
    { term: "Percentage", meaning: "百分数" },
    { term: "Perimeter", meaning: "周长" },
    { term: "Perpendicular", meaning: "垂直" },
    { term: "Pi (π)", meaning: "圆周率" },
    { term: "Pie chart", meaning: "饼图" },
    { term: "Polynomial", meaning: "多项式" },
    { term: "Prime number", meaning: "质数" },
    { term: "Probability", meaning: "概率" },
    { term: "Product", meaning: "积" },
    { term: "Quadrant", meaning: "象限" },
    { term: "Quadratic", meaning: "二次的" },
    { term: "Quotient", meaning: "商" },
    { term: "Radius", meaning: "半径" },
    { term: "Range", meaning: "值域；极差" },
    { term: "Ratio", meaning: "比；比例" },
    { term: "Rational number", meaning: "有理数" },
    { term: "Reciprocal", meaning: "倒数" },
    { term: "Rectangle", meaning: "矩形" },
    { term: "Reflex angle", meaning: "优角" },
    { term: "Right angle", meaning: "直角" },
    { term: "Root", meaning: "根" },
    { term: "Round", meaning: "四舍五入" },
    { term: "Scale", meaning: "比例尺；刻度" },
    { term: "Segment", meaning: "线段；弓形" },
    { term: "Sequence", meaning: "数列" },
    { term: "Simplify", meaning: "化简" },
    { term: "Sine (sin)", meaning: "正弦" },
    { term: "Sphere", meaning: "球体" },
    { term: "Square root", meaning: "平方根" },
    { term: "Standard form", meaning: "标准形式（科学计数法）" },
    { term: "Substitute", meaning: "代入" },
    { term: "Sum", meaning: "和" },
    { term: "Supplementary angles", meaning: "补角" },
    { term: "Tangent (tan)", meaning: "正切" },
    { term: "Term", meaning: "项" },
    { term: "Trapezium", meaning: "梯形" },
    { term: "Triangle", meaning: "三角形" },
    { term: "Variable", meaning: "变量" },
    { term: "Vector", meaning: "向量" },
    { term: "Vertex / Vertices", meaning: "顶点" },
    { term: "Volume", meaning: "体积" },
    { term: "Corresponding angles", meaning: "同位角" },
    { term: "Cross section", meaning: "横截面" },
    { term: "Curve", meaning: "曲线" },
    { term: "Data", meaning: "数据" },
    { term: "Degree", meaning: "度；次数" },
    { term: "Diagonal", meaning: "对角线" },
    { term: "Direct variation", meaning: "正变" },
    { term: "Domain", meaning: "定义域" },
    { term: "Edge", meaning: "棱；边" },
    { term: "Estimate", meaning: "估计" },
    { term: "Exterior angle", meaning: "外角" },
    { term: "Factor theorem", meaning: "因式定理" },
    { term: "Geometric sequence", meaning: "等比数列" },
    { term: "Histogram", meaning: "直方图" },
    { term: "Inverse proportion", meaning: "反比例" },
    { term: "Lateral surface", meaning: "侧面" },
    { term: "Magnitude", meaning: "模；大小" },
    { term: "Mean squared deviation", meaning: "均方偏差" },
    { term: "Net", meaning: "展开图" },
    { term: "Pentagon", meaning: "五边形" },
    { term: "Polygon", meaning: "多边形" },
    { term: "Prism", meaning: "棱柱" },
    { term: "Pyramid", meaning: "棱锥" },
    { term: "Pythagoras' theorem", meaning: "勾股定理" },
    { term: "Quadrilateral", meaning: "四边形" },
    { term: "Sample", meaning: "样本" },
    { term: "Sector", meaning: "扇形" },
    { term: "Similar", meaning: "相似" },
    { term: "Skew", meaning: "偏斜" },
    { term: "Standard deviation", meaning: "标准差" },
    { term: "Symmetry", meaning: "对称" },
    { term: "Tangent (to a circle)", meaning: "切线" },
    { term: "Transformation", meaning: "变换" },
    { term: "Trigonometry", meaning: "三角学" },
    { term: "Unit", meaning: "单位" },
    { term: "Venn diagram", meaning: "韦恩图" },
  ],

  physics: [
    { term: "Acceleration", meaning: "加速度", definition: "速度变化率；单位时间内速度的改变量，矢量，单位 m/s²。" },
    { term: "Amplitude", meaning: "振幅", definition: "振动或波动中质点离开平衡位置的最大位移，反映能量大小。" },
    { term: "Atom", meaning: "原子", definition: "物质的基本单位，由原子核与核外电子组成，化学变化中的最小粒子。" },
    { term: "Atomic number", meaning: "原子序数", definition: "原子核内质子数，决定元素种类，等于核电荷数。" },
    { term: "Beta particle (β)", meaning: "β粒子", definition: "放射性衰变中放出的高速电子或正电子，穿透力强于α粒子。" },
    { term: "Boiling point", meaning: "沸点", definition: "液体沸腾时的温度，此时饱和蒸气压等于外界压强。" },
    { term: "Brownian motion", meaning: "布朗运动", definition: "悬浮微粒在液体或气体中做无规则运动，证明分子在做永不停息的热运动。" },
    { term: "Capacitance", meaning: "电容", definition: "电容器储存电荷的能力，C = Q/V，单位法拉(F)。" },
    { term: "Centre of mass", meaning: "质心", definition: "物体质量集中等效的一点，重力可视为作用于此点。" },
    { term: "Chain reaction", meaning: "链式反应", definition: "核裂变中一个中子引发裂变并产生更多中子，使反应持续进行。" },
    { term: "Charge", meaning: "电荷", definition: "物体带电多少的量度，单位库仑(C)；分正负两种。" },
    { term: "Conduction", meaning: "传导", definition: "热或电通过介质由高温/高电势向低温/低电势传递的过程。" },
    { term: "Conductor", meaning: "导体", definition: "能良好传导热或电的材料，如金属；电阻率低。" },
    { term: "Conservation of energy", meaning: "能量守恒", definition: "能量既不会凭空产生也不会消失，只能从一种形式转化为另一种形式。" },
    { term: "Convection", meaning: "对流", definition: "流体因温度差导致密度差而产生的循环流动传热方式。" },
    { term: "Current", meaning: "电流", definition: "单位时间内通过导体横截面的电荷量，I = Q/t，单位安培(A)。" },
    { term: "Density", meaning: "密度", definition: "单位体积物质的质量，ρ = m/V，单位 kg/m³。" },
    { term: "Diffraction", meaning: "衍射", definition: "波绕过障碍物或通过狭缝时传播方向发生弯曲的现象。" },
    { term: "Efficiency", meaning: "效率", definition: "有用输出与总输入的比值，常用百分数表示；η = 有用输出/总输入。" },
    { term: "Elastic collision", meaning: "弹性碰撞", definition: "碰撞前后系统动能守恒的碰撞；无动能损失。" },
    { term: "Electric field", meaning: "电场", definition: "电荷周围存在的一种物质，对放入其中的电荷有力的作用；E = F/q。" },
    { term: "Electromagnetic wave", meaning: "电磁波", definition: "变化的电场和磁场在空间中传播形成的波；光、无线电波等均属此类。" },
    { term: "Electron", meaning: "电子", definition: "带负电的亚原子粒子，绕核运动；质量很小，带电量 -e。" },
    { term: "Energy", meaning: "能量", definition: "物体做功的本领；形式包括动能、势能、内能、电能等，单位焦耳(J)。" },
    { term: "Force", meaning: "力", definition: "物体间的相互作用，使物体产生加速度或形变；F = ma，单位牛顿(N)。" },
    { term: "Frequency", meaning: "频率", definition: "单位时间内完成振动的次数，f = 1/T，单位赫兹(Hz)。" },
    { term: "Friction", meaning: "摩擦力", definition: "两接触面相对运动或有相对运动趋势时产生的阻碍相对运动的力。" },
    { term: "Gamma radiation (γ)", meaning: "γ射线", definition: "波长极短的电磁波，穿透力强，来自原子核能级跃迁或粒子湮灭。" },
    { term: "Gravitational field strength", meaning: "重力场强度", definition: "单位质量物体所受重力，g = F/m，近似常数 9.8 N/kg。" },
    { term: "Half-life", meaning: "半衰期", definition: "放射性核素衰变到一半所需的时间；表征衰变快慢。" },
    { term: "Hooke's Law", meaning: "胡克定律", definition: "弹性限度内，弹簧弹力与形变量成正比：F = kx。" },
    { term: "Impulse", meaning: "冲量", definition: "力与作用时间的乘积，等于动量的变化量；I = Ft = Δp。" },
    { term: "Inertia", meaning: "惯性", definition: "物体保持原有运动状态的性质；质量是惯性大小的量度。" },
    { term: "Insulator", meaning: "绝缘体", definition: "几乎不导电或导热的材料，如橡胶、塑料、空气。" },
    { term: "Intensity", meaning: "强度", definition: "单位面积上通过的功率或能量流；如光的强度、声强。" },
    { term: "Ion", meaning: "离子", definition: "失去或获得电子而带电的原子或原子团；正离子为阳离子，负离子为阴离子。" },
    { term: "Isotope", meaning: "同位素", definition: "质子数相同、中子数不同的同种元素的不同核素；化学性质相同。" },
    { term: "Kinetic energy", meaning: "动能", definition: "物体因运动而具有的能量；Ek = ½mv²。" },
    { term: "Longitudinal wave", meaning: "纵波", definition: "振动方向与传播方向平行的波，如声波；有疏密区。" },
    { term: "Mass", meaning: "质量", definition: "物体所含物质的多少，惯性大小的量度；单位千克(kg)，标量。" },
    { term: "Mass number", meaning: "质量数", definition: "原子核内质子数与中子数之和，近似等于相对原子质量整数部分。" },
    { term: "Momentum", meaning: "动量", definition: "质量与速度的乘积，p = mv；矢量；守恒定律在碰撞中常用。" },
    { term: "Newton's laws", meaning: "牛顿定律", definition: "第一定律：惯性；第二定律：F=ma；第三定律：作用力与反作用力。" },
    { term: "Nuclear fission", meaning: "核裂变", definition: "重核分裂成较轻核并释放能量的过程；用于核电站与原子弹。" },
    { term: "Nuclear fusion", meaning: "核聚变", definition: "轻核结合成较重核并释放能量的过程；太阳能量来源。" },
    { term: "Ohm's Law", meaning: "欧姆定律", definition: "金属等导体中，电流与电压成正比：V = IR，R 为电阻。" },
    { term: "Potential difference", meaning: "电势差", definition: "两点间电势之差，等于单位正电荷从一点移到另一点电场力做的功；单位伏特(V)。" },
    { term: "Power", meaning: "功率", definition: "单位时间内做功多少，P = W/t = Fv 或 P = IV；单位瓦特(W)。" },
    { term: "Pressure", meaning: "压强", definition: "单位面积上所受正压力，p = F/S；单位帕斯卡(Pa)。" },
    { term: "Radiation", meaning: "辐射", definition: "能量以波或粒子形式在空间传播；热辐射不需介质。" },
    { term: "Refraction", meaning: "折射", definition: "波从一种介质斜射入另一种介质时传播方向发生偏折的现象；遵守折射定律。" },
    { term: "Refractive index", meaning: "折射率", definition: "光在真空中的速度与在该介质中速度之比；n = c/v，n ≥ 1。" },
    { term: "Resistance", meaning: "电阻", definition: "导体对电流的阻碍作用，R = V/I；单位欧姆(Ω)。" },
    { term: "Resonance", meaning: "共振", definition: "驱动频率等于系统固有频率时振幅急剧增大的现象。" },
    { term: "Resultant force", meaning: "合力", definition: "多个力等效为一个力时的矢量和；决定物体加速度。" },
    { term: "Scalar", meaning: "标量", definition: "只有大小没有方向的物理量，如质量、时间、能量、温度。" },
    { term: "Simple harmonic motion (SHM)", meaning: "简谐运动", definition: "加速度与位移成正比且方向相反的周期性运动；如弹簧振子、单摆。" },
    { term: "Specific heat capacity", meaning: "比热容", definition: "单位质量物质升高单位温度所需热量；c = Q/(mΔT)。" },
    { term: "Speed", meaning: "速率", definition: "路程与时间的比值，标量；与速度(矢量)区分。" },
    { term: "Temperature", meaning: "温度", definition: "物体冷热程度的量度，与分子平均动能有关；单位摄氏度或开尔文。" },
    { term: "Terminal velocity", meaning: "终端速度", definition: "物体在流体中下落时阻力与重力平衡时的恒定速度。" },
    { term: "Transformer", meaning: "变压器", definition: "利用电磁感应改变交流电压的装置；Vp/Vs = Np/Ns。" },
    { term: "Transverse wave", meaning: "横波", definition: "振动方向与传播方向垂直的波，如电磁波、绳波。" },
    { term: "Vector", meaning: "矢量", definition: "既有大小又有方向的量，如位移、速度、力、动量；运算遵循平行四边形法则。" },
    { term: "Velocity", meaning: "速度", definition: "位移对时间的变化率，矢量；含大小(速率)与方向。" },
    { term: "Voltage", meaning: "电压", definition: "电势差的俗称；驱动电荷定向移动形成电流。" },
    { term: "Wavelength", meaning: "波长", definition: "波在一个周期内传播的距离，或相邻同相位点之间的距离；单位米(m)。" },
    { term: "Weight", meaning: "重力", definition: "物体所受地球引力，W = mg；与质量不同，会随位置变化。" },
    { term: "Work", meaning: "功", definition: "力在位移方向上的效果，W = Fs cos θ；单位焦耳(J)，与能量转化相关。" },
    { term: "Alpha particle (α)", meaning: "α粒子", definition: "氦核，由 2 质子与 2 中子组成；电离能力强、穿透力弱。" },
    { term: "Critical angle", meaning: "临界角", definition: "光从光密介质射向光疏介质时，折射角为 90° 时的入射角；大于此角发生全反射。" },
    { term: "Dispersion", meaning: "色散", definition: "复色光通过棱镜等分解成单色光的现象；因不同波长折射率不同。" },
    { term: "Electromotive force (e.m.f.)", meaning: "电动势", definition: "电源将其他形式能转化为电能的本领；等于开路时电源两极间电势差，单位伏特(V)。" },
    { term: "Free fall", meaning: "自由落体", definition: "仅受重力、初速为零的运动；加速度为 g，与质量无关。" },
    { term: "Internal resistance", meaning: "内阻", definition: "电源内部对电流的阻碍；导致端电压随电流增大而减小。" },
    { term: "Magnetic field", meaning: "磁场", definition: "磁体或电流周围存在的一种物质，对放入其中的磁极或电流有力的作用。" },
    { term: "Newton (N)", meaning: "牛顿", definition: "力的单位；使 1 kg 物体产生 1 m/s² 加速度的力为 1 N。" },
    { term: "Period", meaning: "周期", definition: "完成一次全振动所需时间，T = 1/f；单位秒(s)。" },
    { term: "Potential energy", meaning: "势能", definition: "由物体位置或形变决定的能量；如重力势能 Ep = mgh、弹性势能。" },
    { term: "Power (P)", meaning: "功率", definition: "单位时间内做功的多少，P = W/t = IV（电）；单位瓦特(W)。" },
    { term: "Reflection", meaning: "反射", definition: "波遇到界面返回原介质的现象；入射角等于反射角。" },
    { term: "Resultant", meaning: "合力/合矢量", definition: "多个力或矢量等效为一个时的矢量和。" },
    { term: "Specific latent heat", meaning: "比潜热", definition: "单位质量物质在相变时吸收或放出的热量；分熔化与汽化。" },
    { term: "Wave speed", meaning: "波速", definition: "波传播的快慢，v = fλ；由介质决定。" },
  ],

  chemistry: [
    { term: "Acid", meaning: "酸", definition: "在水溶液中电离出 H⁺、pH < 7 的化合物；可与碱中和生成盐和水。" },
    { term: "Activation energy", meaning: "活化能", definition: "反应物变成活化络合物所需的最小能量；催化剂降低活化能。" },
    { term: "Alkali", meaning: "碱", definition: "可溶性碱；在水溶液中电离出 OH⁻，pH > 7，如 NaOH、KOH。" },
    { term: "Alkane", meaning: "烷烃", definition: "只含 C-C、C-H 单键的饱和烃，通式 CnH2n+2；如甲烷、乙烷。" },
    { term: "Alkene", meaning: "烯烃", definition: "含至少一个 C=C 双键的不饱和烃，通式 CnH2n；可发生加成反应。" },
    { term: "Alloy", meaning: "合金", definition: "两种或多种金属（或金属与非金属）熔合而成的具有金属特性的物质。" },
    { term: "Anion", meaning: "阴离子", definition: "带负电荷的离子，由原子或原子团得电子形成；电解时移向阳极。" },
    { term: "Anode", meaning: "阳极", definition: "电解或原电池中发生氧化反应的电极；正离子移向阴极，负离子移向阳极。" },
    { term: "Atom", meaning: "原子", definition: "化学变化中的最小粒子；由原子核与核外电子构成。" },
    { term: "Atomic structure", meaning: "原子结构", definition: "原子由质子、中子组成的原子核与核外电子构成；质子数决定元素种类。" },
    { term: "Base", meaning: "碱", definition: "能接受质子或提供 OH⁻ 的物质；与酸反应生成盐和水。" },
    { term: "Boiling point", meaning: "沸点", definition: "液体饱和蒸气压等于外界压强时的温度；与分子间作用力有关。" },
    { term: "Bond", meaning: "键", definition: "原子或离子之间的强烈相互作用；类型包括离子键、共价键、金属键。" },
    { term: "Catalyst", meaning: "催化剂", definition: "改变化学反应速率而自身在反应前后质量和化学性质不变的物质。" },
    { term: "Cathode", meaning: "阴极", definition: "电解或原电池中发生还原反应的电极；正离子在此得电子。" },
    { term: "Cation", meaning: "阳离子", definition: "带正电荷的离子，由原子或原子团失电子形成；电解时移向阴极。" },
    { term: "Combustion", meaning: "燃烧", definition: "物质与氧气发生的剧烈氧化反应，常放热发光；烃燃烧生成 CO₂ 和 H₂O。" },
    { term: "Compound", meaning: "化合物", definition: "由两种或多种元素按固定比例通过化学键结合而成的纯净物。" },
    { term: "Concentration", meaning: "浓度", definition: "单位体积或单位质量溶液中所含溶质的量；常用 mol/dm³ 或 g/dm³。" },
    { term: "Covalent bond", meaning: "共价键", definition: "原子间通过共用电子对形成的化学键；常见于非金属之间。" },
    { term: "Cracking", meaning: "裂解", definition: "长链烃在高温或催化剂作用下断裂成较短链烃的过程；用于制烯烃和汽油。" },
    { term: "Displacement reaction", meaning: "置换反应", definition: "一种单质与化合物反应生成另一种单质和化合物的反应；如金属与酸、金属与盐。" },
    { term: "Distillation", meaning: "蒸馏", definition: "利用沸点差异分离液体混合物的方法；简单蒸馏与分馏。" },
    { term: "Electrolysis", meaning: "电解", definition: "电流通过电解质溶液或熔融物时在电极上发生的氧化还原过程。" },
    { term: "Electron", meaning: "电子", definition: "带负电的亚原子粒子，绕核运动；参与成键与氧化还原。" },
    { term: "Element", meaning: "元素", definition: "由相同质子数的一类原子组成的纯净物；不能由化学方法再分。" },
    { term: "Empirical formula", meaning: "实验式", definition: "表示化合物中各元素原子最简整数比的化学式。" },
    { term: "Endothermic", meaning: "吸热的", definition: "吸收热量的过程或反应；ΔH > 0，如多数分解反应、溶解某些盐。" },
    { term: "Equilibrium", meaning: "平衡", definition: "正逆反应速率相等、各物质浓度不再宏观变化的状态；动态平衡。" },
    { term: "Exothermic", meaning: "放热的", definition: "放出热量的过程或反应；ΔH < 0，如燃烧、中和、多数化合反应。" },
    { term: "Filtration", meaning: "过滤", definition: "分离不溶性固体与液体的操作；需滤纸与漏斗。" },
    { term: "Formula", meaning: "化学式", definition: "用元素符号和数字表示物质组成的式子；分子式、实验式、结构式等。" },
    { term: "Functional group", meaning: "官能团", definition: "决定有机物主要化学性质的原子或原子团；如 -OH、-COOH、C=C。" },
    { term: "Galvanising", meaning: "镀锌", definition: "在铁表面镀锌以防锈；锌优先腐蚀保护铁。" },
    { term: "Group", meaning: "族", definition: "周期表中纵列；同族元素价电子数相同，化学性质相似。" },
    { term: "Halogen", meaning: "卤素", definition: "第ⅦA 族元素 F、Cl、Br、I、At；活泼非金属，易得电子成 -1 价。" },
    { term: "Hydrocarbon", meaning: "烃", definition: "只含碳和氢的有机物；分为烷烃、烯烃、炔烃、芳香烃等。" },
    { term: "Indicator", meaning: "指示剂", definition: "通过颜色变化指示 pH 或滴定终点的物质；如酚酞、石蕊、甲基橙。" },
    { term: "Ion", meaning: "离子", definition: "带电的原子或原子团；阳离子带正电，阴离子带负电。" },
    { term: "Ionic bond", meaning: "离子键", definition: "阴阳离子之间通过静电作用形成的化学键；典型存在于离子化合物中。" },
    { term: "Isotope", meaning: "同位素", definition: "质子数相同、中子数不同的同种元素的不同原子；化学性质相同。" },
    { term: "Mass number", meaning: "质量数", definition: "原子核内质子数与中子数之和；写在元素符号左上角。" },
    { term: "Melting point", meaning: "熔点", definition: "固体与液体平衡共存时的温度；与晶体类型、键型有关。" },
    { term: "Metal", meaning: "金属", definition: "具有光泽、导电导热、延展性的一类元素；易失电子形成阳离子。" },
    { term: "Mixture", meaning: "混合物", definition: "由两种或多种物质混合而成、各组分保持原有性质、无固定组成的物质。" },
    { term: "Mole", meaning: "摩尔", definition: "物质的量的单位；1 mol 含 6.02×10²³ 个粒子（阿伏伽德罗常数）。" },
    { term: "Molecular formula", meaning: "分子式", definition: "表示分子中各类原子实际数目的化学式。" },
    { term: "Neutralisation", meaning: "中和", definition: "酸与碱反应生成盐和水的反应；实质为 H⁺ + OH⁻ → H₂O。" },
    { term: "Neutron", meaning: "中子", definition: "原子核中不带电的粒子；质量约等于质子，与质子共同构成质量数。" },
    { term: "Noble gas", meaning: "稀有气体", definition: "第 0 族元素 He、Ne、Ar 等；外层电子稳定，化学性质极不活泼。" },
    { term: "Non-metal", meaning: "非金属", definition: "通常不具金属光泽、导电性较差的一类元素；常得电子或共用电子。" },
    { term: "Nucleus", meaning: "原子核", definition: "原子中心由质子和中子组成的带正电部分；几乎集中全部质量。" },
    { term: "Oxidation", meaning: "氧化", definition: "失去电子或氧化数升高的过程；与还原同时发生。" },
    { term: "Oxidising agent", meaning: "氧化剂", definition: "使其他物质氧化而自身被还原的物质；得电子。" },
    { term: "Period", meaning: "周期", definition: "周期表中的横排；同周期元素电子层数相同。" },
    { term: "Periodic table", meaning: "周期表", definition: "按原子序数排列元素的表格；反映周期律与族、周期规律。" },
    { term: "pH", meaning: "pH", definition: "表示溶液酸碱度的量；pH = -lg[H⁺]，7 为中性，<7 酸性，>7 碱性。" },
    { term: "Precipitation", meaning: "沉淀", definition: "溶液中发生反应生成难溶固体析出的过程；沉淀反应可用于分离或鉴定。" },
    { term: "Product", meaning: "生成物", definition: "化学反应中生成的物质；写在方程式的右侧。" },
    { term: "Proton", meaning: "质子", definition: "原子核中带正电的粒子；质子数 = 原子序数 = 核电荷数。" },
    { term: "Reactant", meaning: "反应物", definition: "参加化学反应的物质；写在方程式的左侧。" },
    { term: "Reactivity series", meaning: "活动性顺序", definition: "金属按失电子能力从强到弱排列的顺序；用于判断置换反应能否发生。" },
    { term: "Reduction", meaning: "还原", definition: "得到电子或氧化数降低的过程；与氧化同时发生。" },
    { term: "Reducing agent", meaning: "还原剂", definition: "使其他物质还原而自身被氧化的物质；失电子。" },
    { term: "Salt", meaning: "盐", definition: "酸与碱中和或酸与金属/碱性氧化物等反应生成的化合物；由金属离子与酸根组成。" },
    { term: "Solubility", meaning: "溶解度", definition: "一定温度、压强下某物质在 100g 溶剂中达到饱和时溶解的质量（或物质的量）。" },
    { term: "Solution", meaning: "溶液", definition: "溶质分散在溶剂中形成的均一、稳定的混合物。" },
    { term: "Solvent", meaning: "溶剂", definition: "溶解其他物质的物质；水是最常见溶剂。" },
    { term: "State symbol", meaning: "状态符号", definition: "化学方程式中表示物质状态的符号：(s) 固、(l) 液、(g) 气、(aq) 水溶液。" },
    { term: "Structural formula", meaning: "结构式", definition: "用短线表示化学键、写出原子连接方式的化学式。" },
    { term: "Sublimation", meaning: "升华", definition: "固体直接变为气体而不经过液体的过程；如碘、干冰。" },
    { term: "Substance", meaning: "物质", definition: "具有固定组成和性质的纯净物；单质或化合物。" },
    { term: "Titration", meaning: "滴定", definition: "将已知浓度的溶液滴入待测溶液至反应完全，通过体积与浓度计算含量的方法。" },
    { term: "Valence electron", meaning: "价电子", definition: "原子最外层参与成键的电子；主族元素价电子数等于族序数。" },
    { term: "Alcohol", meaning: "醇", definition: "含 -OH 羟基的烃的衍生物；如乙醇；可氧化为醛、羧酸。" },
    { term: "Aldehyde", meaning: "醛", definition: "含 -CHO 羰基的有机物；可被氧化为羧酸、被还原为醇。" },
    { term: "Alkaline earth metal", meaning: "碱土金属", definition: "第ⅡA 族元素 Be、Mg、Ca、Sr、Ba、Ra；常见 +2 价。" },
    { term: "Alkyl group", meaning: "烷基", definition: "烷烃去掉一个氢后的基团，如 -CH₃ 甲基、-C₂H₅ 乙基。" },
    { term: "Amphoteric", meaning: "两性的", definition: "既能与酸又能与碱反应的物质；如 Al₂O₃、氨基酸。" },
    { term: "Aromatic compound", meaning: "芳香族化合物", definition: "含苯环或类似结构的有机物；具有特殊稳定性。" },
    { term: "Avogadro constant", meaning: "阿伏伽德罗常数", definition: "1 mol 粒子所含的粒子数，约 6.02×10²³ mol⁻¹。" },
    { term: "Carbonyl group", meaning: "羰基", definition: "C=O 双键；醛、酮、羧酸等均含此官能团。" },
    { term: "Carboxylic acid", meaning: "羧酸", definition: "含 -COOH 羧基的有机物；具酸性，可与碱、醇等反应。" },
    { term: "Catalyst", meaning: "催化剂", definition: "改变化学反应速率而自身在反应前后质量和化学性质不变的物质。" },
    { term: "Collision theory", meaning: "碰撞理论", definition: "反应物分子必须发生有效碰撞（足够能量、正确取向）才能反应。" },
    { term: "Condensation", meaning: "缩合", definition: "两个分子脱去小分子（如 H₂O）生成较大分子的反应；如酯化、肽键形成。" },
    { term: "Ester", meaning: "酯", definition: "羧酸与醇脱水形成的化合物；有香味，可水解为酸和醇。" },
    { term: "Fermentation", meaning: "发酵", definition: "微生物无氧分解有机物；如葡萄糖发酵得乙醇和 CO₂。" },
    { term: "Halide", meaning: "卤化物", definition: "卤素与另一种元素形成的化合物；如 NaCl、CH₃Cl。" },
    { term: "Hydrocarbon", meaning: "烃", definition: "只含碳和氢的有机物；烷烃、烯烃、炔烃、芳香烃等。" },
    { term: "Hydrogen bond", meaning: "氢键", definition: "与 N、O、F 等相连的 H 与另一分子中 N、O、F 之间的较强作用；影响沸点、溶解度。" },
    { term: "Molar mass", meaning: "摩尔质量", definition: "单位物质的量的质量，数值等于相对分子质量 g/mol。" },
    { term: "Oxidation number", meaning: "氧化数", definition: "化合物中某元素按规则得到的表观电荷数；用于判断氧化还原。" },
    { term: "Polymer", meaning: "聚合物", definition: "由许多小分子（单体）通过共价键连接成的大分子；如塑料、橡胶。" },
    { term: "Precipitation reaction", meaning: "沉淀反应", definition: "溶液中离子结合生成难溶固体的反应；用于鉴定或分离离子。" },
    { term: "Rate of reaction", meaning: "反应速率", definition: "单位时间内反应物浓度减少或生成物浓度增加的量；受浓度、温度、催化剂等影响。" },
    { term: "Redox", meaning: "氧化还原", definition: "氧化与还原同时发生的反应；有电子转移或氧化数变化。" },
    { term: "Saturated", meaning: "饱和的", definition: "有机中指只含单键；溶液中指溶解达平衡、不能再溶更多溶质。" },
    { term: "Stoichiometry", meaning: "化学计量", definition: "化学反应中反应物与生成物之间的物质的量关系。" },
    { term: "Transition element", meaning: "过渡元素", definition: "周期表 d 区元素；多可变价态、有色离子、催化性。" },
  ],

  economics: [
    { term: "Aggregate demand (AD)", meaning: "总需求", definition: "在某一价格水平下，经济中所有部门计划购买的产品与服务的总量；AD = C + I + G + (X - M)。" },
    { term: "Aggregate supply (AS)", meaning: "总供给", definition: "在某一价格水平下，经济中所有生产者愿意并能够提供的产品与服务的总量。" },
    { term: "Allocative efficiency", meaning: "配置效率", definition: "资源分配使社会总福利最大；当边际社会效益等于边际社会成本时达到。" },
    { term: "Average cost", meaning: "平均成本", definition: "单位产量的成本；AC = TC / Q；含平均固定成本与平均可变成本。" },
    { term: "Balance of payments", meaning: "国际收支", definition: "一定时期内一国与外国之间全部经济交易的系统记录；含经常账户与资本与金融账户。" },
    { term: "Barrier to entry", meaning: "进入壁垒", definition: "阻止新企业进入某行业的因素；如专利、规模经济、品牌、法规。" },
    { term: "Capital", meaning: "资本", definition: "生产中用到的机器、设备、厂房等 man-made 生产资料；生产要素之一。" },
    { term: "Ceteris paribus", meaning: "其他条件不变", definition: "经济学分析中假设除所研究变量外其他因素保持不变，以分析单一变量影响。" },
    { term: "Competition", meaning: "竞争", definition: "多个生产者或消费者为有限资源或交易机会而争夺；可提高效率、压低价格。" },
    { term: "Consumer surplus", meaning: "消费者剩余", definition: "消费者愿意支付的最高价格与实际支付价格之差的总和；衡量消费者福利。" },
    { term: "Consumption", meaning: "消费", definition: "家庭为满足当前需要而购买产品与服务的支出；AD 组成部分之一。" },
    { term: "Cost-push inflation", meaning: "成本推动型通货膨胀", definition: "因生产成本上升（如工资、原材料）导致的总体物价上涨。" },
    { term: "Demand", meaning: "需求", definition: "在某一时期内，消费者在不同价格水平下愿意并且能够购买的产品数量；通常与价格负相关。" },
    { term: "Demand-pull inflation", meaning: "需求拉动型通货膨胀", definition: "因总需求超过总供给导致的总体物价上涨。" },
    { term: "Demerit good", meaning: "负外部性商品", definition: "消费会产生负外部性、社会希望减少消费的商品；如烟酒，政府可能征税或管制。" },
    { term: "Depreciation", meaning: "贬值（货币）", definition: "浮动汇率下本国货币对外国货币的汇率下降；出口更便宜、进口更贵。" },
    { term: "Division of labour", meaning: "劳动分工", definition: "将生产过程拆分为不同工序由不同人完成；提高专业化与效率。" },
    { term: "Economic growth", meaning: "经济增长", definition: "实际 GDP 或人均实际 GDP 的持续增加；常用年度增长率衡量。" },
    { term: "Economic development", meaning: "经济发展", definition: "除收入增长外，还包括生活水平、教育、健康、平等方面的改善。" },
    { term: "Economies of scale", meaning: "规模经济", definition: "产量增加时单位成本下降；源于专业化、采购与融资优势等。" },
    { term: "Elasticity", meaning: "弹性", definition: "一变量对另一变量变化的敏感程度；如需求价格弹性、供给价格弹性。" },
    { term: "Enterprise", meaning: "企业家才能", definition: "组织其他生产要素、承担风险、做出决策的能力；生产要素之一。" },
    { term: "Equilibrium", meaning: "均衡", definition: "供求相等、无内在趋势使价格或数量改变的状态；市场出清。" },
    { term: "Externality", meaning: "外部性", definition: "生产或消费对第三方产生的未在价格中反映的收益或成本；导致市场失灵。" },
    { term: "Factors of production", meaning: "生产要素", definition: "生产所需投入：土地、劳动、资本、企业家才能。" },
    { term: "Fiscal policy", meaning: "财政政策", definition: "政府通过税收与政府支出影响总需求与经济的政策。" },
    { term: "Fixed cost", meaning: "固定成本", definition: "不随产量变化的成本；如租金、管理层工资；短期内存在。" },
    { term: "Free market", meaning: "自由市场", definition: "主要由供求决定价格与资源配置、政府干预最少的经济体制。" },
    { term: "GDP (Gross Domestic Product)", meaning: "国内生产总值", definition: "一定时期内一国境内生产的全部最终产品与服务的市场价值总和。" },
    { term: "Government spending", meaning: "政府支出", definition: "政府在公共产品、服务、转移支付上的支出；AD 组成部分之一。" },
    { term: "Inferior good", meaning: "劣等品", definition: "收入增加时需求减少的商品；需求收入弹性为负。" },
    { term: "Inflation", meaning: "通货膨胀", definition: "一般物价水平持续上涨；导致货币购买力下降。" },
    { term: "Investment", meaning: "投资", definition: "企业购买资本品以扩大生产能力的支出；AD 组成部分之一。" },
    { term: "Labour", meaning: "劳动", definition: "生产中投入的人力 effort；生产要素之一。" },
    { term: "Land", meaning: "土地", definition: "自然资源的总称；生产要素之一。" },
    { term: "Law of demand", meaning: "需求定律", definition: "其他条件不变时，价格上升则需求量减少，价格下降则需求量增加。" },
    { term: "Law of supply", meaning: "供给定律", definition: "其他条件不变时，价格上升则供给量增加，价格下降则供给量减少。" },
    { term: "Marginal cost", meaning: "边际成本", definition: "每增加一单位产量所增加的总成本；MC = ΔTC / ΔQ。" },
    { term: "Marginal revenue", meaning: "边际收益", definition: "每多销售一单位产品所增加的总收益；完全竞争时 MR = P。" },
    { term: "Market", meaning: "市场", definition: "买方与卖方进行交易的场所或机制；可指产品市场或要素市场。" },
    { term: "Market failure", meaning: "市场失灵", definition: "市场未能有效配置资源、未能实现社会福利最大；原因包括外部性、公共品、垄断等。" },
    { term: "Merit good", meaning: "优效品", definition: "社会认为应鼓励消费、往往存在正外部性或信息不足的商品；如教育、医疗。" },
    { term: "Monetary policy", meaning: "货币政策", definition: "央行通过利率、货币供给等影响总需求与经济的政策。" },
    { term: "Monopoly", meaning: "垄断", definition: "市场上只有一个供应商；可定高价、存在进入壁垒、可能导致配置无效率。" },
    { term: "Normal good", meaning: "正常品", definition: "收入增加时需求增加的商品；需求收入弹性为正。" },
    { term: "Opportunity cost", meaning: "机会成本", definition: "做出某一选择所放弃的次优选择的价值；稀缺性下的核心概念。" },
    { term: "Perfect competition", meaning: "完全竞争", definition: "大量企业、同质产品、自由进出、完全信息；企业为价格接受者。" },
    { term: "Price elasticity of demand (PED)", meaning: "需求价格弹性", definition: "需求量变化百分比与价格变化百分比之比；衡量需求对价格的反应程度。" },
    { term: "Price elasticity of supply (PES)", meaning: "供给价格弹性", definition: "供给量变化百分比与价格变化百分比之比；衡量供给对价格的反应程度。" },
    { term: "Producer surplus", meaning: "生产者剩余", definition: "生产者实际获得的价格与愿意接受的最低价格之差的总和。" },
    { term: "Production", meaning: "生产", definition: "将生产要素转化为产品与服务的过程。" },
    { term: "Productive efficiency", meaning: "生产效率", definition: "在最低平均成本处生产；资源不浪费。" },
    { term: "Public good", meaning: "公共品", definition: "非竞争性且非排他性的产品；如国防、路灯；市场难以足量提供。" },
    { term: "Scarcity", meaning: "稀缺性", definition: "资源有限而欲望无限；经济学研究如何在稀缺下做出选择。" },
    { term: "Subsidy", meaning: "补贴", definition: "政府向生产者或消费者支付的款项以降低价格或增加产量；常用于正外部性或弱势产业。" },
    { term: "Supply", meaning: "供给", definition: "在某一时期内，生产者在不同价格水平下愿意并且能够提供的产品数量；通常与价格正相关。" },
    { term: "Tariff", meaning: "关税", definition: "对进口商品征收的税；提高进口品价格、保护国内产业。" },
    { term: "Tax", meaning: "税收", definition: "政府强制征收的款项；用于筹资与再分配；可影响行为（如间接税）。" },
    { term: "Total cost", meaning: "总成本", definition: "生产一定产量所发生的全部成本；TC = FC + VC。" },
    { term: "Total revenue", meaning: "总收益", definition: "销售一定数量产品所得的全部收入；TR = P × Q。" },
    { term: "Trade", meaning: "贸易", definition: "商品与服务的交换；国际贸易基于比较优势与分工。" },
    { term: "Unemployment", meaning: "失业", definition: "愿意且能够工作的人找不到工作；常用失业率衡量。" },
    { term: "Variable cost", meaning: "可变成本", definition: "随产量变化的成本；如原材料、计件工资。" },
    { term: "Welfare", meaning: "福利", definition: "个人或社会的经济福祉；常以消费者剩余、生产者剩余及外部性综合衡量。" }
  ]
};

